use_frameworks!

platform :ios, '14.0'

target 'Session-Manager_Example' do
  pod 'Session-Manager', :path => '../'

  target 'Session-Manager_Tests' do
    inherit! :search_paths

    post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                 end
            end
     end
end
end
end
